// <auto-generated />
using System;
using KT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KT.Migrations
{
    [DbContext(typeof(Test1Context))]
    [Migration("20241221145425_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChiTietDangKy", b =>
                {
                    b.Property<int>("MaDk")
                        .HasColumnType("int")
                        .HasColumnName("MaDK");

                    b.Property<string>("MaHp")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasColumnName("MaHP")
                        .IsFixedLength();

                    b.HasKey("MaDk", "MaHp")
                        .HasName("PK__ChiTietD__F557DC0284907DC5");

                    b.HasIndex("MaHp");

                    b.ToTable("ChiTietDangKy", (string)null);
                });

            modelBuilder.Entity("KT.Models.DangKy", b =>
                {
                    b.Property<int>("MaDk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDk"));

                    b.Property<string>("MaSv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("MaSV")
                        .IsFixedLength();

                    b.Property<DateOnly?>("NgayDk")
                        .HasColumnType("date")
                        .HasColumnName("NgayDK");

                    b.HasKey("MaDk")
                        .HasName("PK__DangKy__2725866C5E56A861");

                    b.HasIndex("MaSv");

                    b.ToTable("DangKy", (string)null);
                });

            modelBuilder.Entity("KT.Models.HocPhan", b =>
                {
                    b.Property<string>("MaHp")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("char(6)")
                        .HasColumnName("MaHP")
                        .IsFixedLength();

                    b.Property<int?>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenHp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenHP");

                    b.HasKey("MaHp")
                        .HasName("PK__HocPhan__2725A6EC674C9B0B");

                    b.ToTable("HocPhan", (string)null);
                });

            modelBuilder.Entity("KT.Models.NganhHoc", b =>
                {
                    b.Property<string>("MaNganh")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<string>("TenNganh")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaNganh")
                        .HasName("PK__NganhHoc__A2CEF50DEA666229");

                    b.ToTable("NganhHoc", (string)null);
                });

            modelBuilder.Entity("KT.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .HasColumnName("MaSV")
                        .IsFixedLength();

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Hinh")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNganh")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.HasKey("MaSv")
                        .HasName("PK__SinhVien__2725081ACCA00EBA");

                    b.HasIndex("MaNganh");

                    b.ToTable("SinhVien", (string)null);
                });

            modelBuilder.Entity("ChiTietDangKy", b =>
                {
                    b.HasOne("KT.Models.DangKy", null)
                        .WithMany()
                        .HasForeignKey("MaDk")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDan__MaDK__412EB0B6");

                    b.HasOne("KT.Models.HocPhan", null)
                        .WithMany()
                        .HasForeignKey("MaHp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDan__MaHP__4222D4EF");
                });

            modelBuilder.Entity("KT.Models.DangKy", b =>
                {
                    b.HasOne("KT.Models.SinhVien", "MaSvNavigation")
                        .WithMany("DangKies")
                        .HasForeignKey("MaSv")
                        .HasConstraintName("FK__DangKy__MaSV__3E52440B");

                    b.Navigation("MaSvNavigation");
                });

            modelBuilder.Entity("KT.Models.SinhVien", b =>
                {
                    b.HasOne("KT.Models.NganhHoc", "MaNganhNavigation")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaNganh")
                        .HasConstraintName("FK__SinhVien__MaNgan__398D8EEE");

                    b.Navigation("MaNganhNavigation");
                });

            modelBuilder.Entity("KT.Models.NganhHoc", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("KT.Models.SinhVien", b =>
                {
                    b.Navigation("DangKies");
                });
#pragma warning restore 612, 618
        }
    }
}
